# Generated by Django 2.1 on 2018-10-29 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigacion',
            name='content',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
