# Generated by Django 2.1 on 2018-10-29 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigacion', '0002_auto_20181029_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigacion',
            name='content',
            field=models.FileField(null=True, upload_to='media/'),
        ),
    ]
